개선된 회원탈퇴 기능 구현
PrayHelper/uspray-frontend pull request #167
Opened 2023-11-24 11:37 UTC by limeojin363

# Summary
- 추가로 백엔드에 전달하는 정보 없이 지정한 계정 삭제만 처리하던 것에서, 탈퇴 사유와 함께 처리하도록 변경하였습니다.
- 탈퇴사유를 선택 / 작성하는 OptionList UI를 작성하였습니다.
- 변경된 API 스펙에 맞춰 호출 코드를 변경하였습니다.

2023-12-03 10:34 UTC, limeojin363 commented
https://github.com/PrayHelper/uspray-frontend/pull/168

여기서 리뷰받은 사항 반영이 필요합니다.

2023-12-21 17:07 UTC, alicehrk requested changes

2023-12-21 17:07 UTC, alicehrk commented on src/pages/DeleteUser.js
> +    line-height: normal;
이러한 기본 스타일들도 명시적으로 사용하는 이유가 있는지 궁금합니다!

2023-12-21 17:19 UTC, limeojin363 commented on src/pages/DeleteUser.js
> +    line-height: normal;
이거분명 고쳐야겠다고 생각했었는데 어째서 제가 이걸 냅둔채로 리뷰요청을 했을까요??

2023-12-21 17:19 UTC, limeojin363 commented on src/pages/DeleteUser.js
> +    line-height: normal;
얼른고치겠습니다

2023-12-21 17:20 UTC, alicehrk commented on src/pages/DeleteUser.js
> +    line-height: normal;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ알겠습니당😁

2023-12-21 19:28 UTC, alicehrk approved these changes

2023-12-21 19:30 UTC, limeojin363 commented
## 추가 작업사항

- 회원탈퇴 시 메인으로 navigate되던 것을, '탈퇴 완료' 상태를 노출하도록 변경하였습니다.
![image](https://github.com/PrayHelper/uspray-frontend/assets/97388599/db8e8eb5-feb4-4ebe-b233-19ae444a7969)

2023-12-21 19:30 UTC, merged