feat: 회원정보 변경 api 연결 및 구조 변경
PrayHelper/uspray-frontend pull request #212
Opened 2024-01-06 08:29 UTC by 200516bb

**API 연결**
- /member/check-pw [POST]

**수정사항**
- 회원정보 변경에서 비밀번호 확인 api 연결
- 회원정보 변경의 구조를 페이지 이동이 아닌 state로 관리하도록 변경

**TODO**
- 비밀번호 변경 (토큰 필요) api가 생기면 연결
- 회원탈퇴 부분 연결

2024-01-06 15:38 UTC, alicehrk requested changes

2024-01-06 15:38 UTC, alicehrk commented on src/pages/CheckInfo.js
> +                    {(pwCheck(password) && !disabled) ? <NextArrow_white/>
여기 부분 수빈싀가 한거 아닌거 알지만 혹시 네이밍 변경해줄 수 있나용..?

2024-01-06 15:38 UTC, alicehrk commented on src/components/ChangeInfo/ChangePhoneNumber.js
> +  z-index: 101;
우리 z-index가 상당히 이곳저곳에서 쓰이는 것 같아서 정리가 한 번 필요할 것 같은데..
혹시 이 101이라는 값은 다른 z-index와 비교해서 결정된 값인가요?? 아니면 임의로..?

2024-01-08 14:42 UTC, 200516bb commented on src/pages/CheckInfo.js
> +                    {(pwCheck(password) && !disabled) ? <NextArrow_white/>
엇 어떤 부분을 말하는거죠..?!

2024-01-08 14:47 UTC, 200516bb commented on src/components/ChangeInfo/ChangePhoneNumber.js
> +  z-index: 101;
그 전 화면인 ChangeInfo의 z-index를 100으로 설정해서 그 위에 쌓이는 ChangePhoneNumber의 z-index를 101로 줬습니당
이렇게 z-index를 하나씩 올리면서 화면을 쌓는게 좋은방법인진 모르겠습니다..ㅠ
그리고 toast의 z-index가 아마 105?인가 일거예요 그래서 모든 화면들의 z-index가 105가 안넘어가게 하도록 해야할 것 같아요!

2024-01-08 14:58 UTC, alicehrk commented on src/pages/CheckInfo.js
> +                    {(pwCheck(password) && !disabled) ? <NextArrow_white/>
NextArrow_white요!

2024-01-08 14:58 UTC, alicehrk commented on src/components/ChangeInfo/ChangePhoneNumber.js
> +  z-index: 101;
아하 알겠습니다 고마워요!

2024-01-09 13:50 UTC, alicehrk approved these changes

2024-01-15 11:30 UTC, merged