Feature/new locker
PrayHelper/uspray-frontend pull request #214
Opened 2024-01-11 17:24 UTC by graS2e

- 보관함 삭제 /share [DELETE]
- 보관함 연타 문제 해결
- 보관함 조회 /share [GET]

2024-01-13 14:28 UTC, alicehrk requested changes

2024-01-13 14:28 UTC, alicehrk commented on src/pages/Locker.js
69-70라인에 있는 콘솔 확인했으면 지워주세요!

2024-01-13 14:28 UTC, alicehrk commented on src/pages/Locker.js
>      let pray_id_list = []; // 빈 배열을 초기화하여 pray_id_list를 설정합니다.
네이밍 컨벤션 camelCase로 수정 부탁드립니당!

2024-01-13 14:28 UTC, alicehrk commented on src/pages/Locker.js
> +  line-height: 23px;
요거 지정한 다른 이유가 있을까요??

2024-01-13 14:28 UTC, alicehrk commented on src/pages/Locker.js
> +  line-height: 23px;
line-height요!

2024-01-13 14:28 UTC, alicehrk commented on src/pages/Locker.js
> +  padding: 0;
하단에 padding: 20px 중복 지정해주던데 확인 부탁드림니당

2024-01-13 14:28 UTC, alicehrk commented on src/pages/Locker.js
> +  background: inherit;
이친구는 어떤 용도로 사용하나요??

2024-01-14 15:29 UTC, graS2e commented on src/pages/Locker.js
지웠습니다!

2024-01-14 15:39 UTC, graS2e commented on src/pages/Locker.js
>      let pray_id_list = []; // 빈 배열을 초기화하여 pray_id_list를 설정합니다.
수정했습니당!

2024-01-14 15:41 UTC, graS2e commented on src/pages/Locker.js
> +  line-height: 23px;
없어서 지웠습니다!

2024-01-14 15:43 UTC, graS2e commented on src/pages/Locker.js
> +  padding: 0;
상하에만 주게끔 수정했슴니당

2024-01-14 15:44 UTC, graS2e commented on src/pages/Locker.js
> +  background: inherit;
사용 안 해서 지웠습니다!!

2024-01-16 06:46 UTC, alicehrk approved these changes

2024-01-16 06:53 UTC, merged