Feature/manage pray
PrayHelper/uspray-frontend pull request #216
Opened 2024-01-12 04:17 UTC by graS2e

- 기도 완료하기 /pray/{prayId}/complete [PUT]
- 기도 삭제하기 /pray/{prayId} [DELETE]
- 기도 수정하기 /pray/{prayId} [PUT]

2024-01-14 14:59 UTC, alicehrk requested changes

2024-01-14 14:59 UTC, alicehrk commented on src/hooks/useManagePray.js
> +  const { mutate: deletePray } = useMutation(
useSendPrayItem에 있는 deletePray랑은 다른 동작을 하나요??

2024-01-14 15:17 UTC, graS2e commented on src/hooks/useManagePray.js
> +  const { mutate: deletePray } = useMutation(
안 사용하게 돼서 삭제했습니다

2024-01-15 13:59 UTC, alicehrk requested changes

2024-01-15 13:59 UTC, alicehrk commented on src/hooks/useSendPrayItem.js
이 hook의 이름을 혹시 usePray와 같은 것으로 바꾸는 건 어떤가요..? delete 기능도 포함되어 있어서 send라고 하면 조금 헷갈릴 것 같습니다!

2024-01-15 14:12 UTC, graS2e commented on src/hooks/useSendPrayItem.js
usePray가 이미 있어서 1.0에서 사용하는 hook으로 바꿨는데 리팩 때 그 부분도 수정하면 좋을 것 같습니다
지금 usePray를 usePrayList 등으로 바꾼다든가?

2024-01-17 14:57 UTC, alicehrk commented on src/hooks/useSendPrayItem.js
알겠습니다!

2024-01-18 06:40 UTC, merged