Feature/kakao naver api
PrayHelper/uspray-frontend pull request #231
Opened 2024-01-29 11:58 UTC by limeojin363

2024-01-30 14:28 UTC, alicehrk commented
혹시 제가 예전에 리뷰했었나요? 아니면 처음인가요?

2024-01-31 07:04 UTC, limeojin363 commented
처음..으로 보입니다

2024-01-31 13:47 UTC, alicehrk requested changes

2024-01-31 13:47 UTC, alicehrk commented on src/pages/Login.js
>      console.log("continueWithApple");
요거 다 썼으면 지워도 되나요??

2024-01-31 13:47 UTC, alicehrk commented on src/pages/SocialLoginNameInput.js
> +        console.log("refresh: ", await getRefreshToken());
얘네도 필요없으면 지워둡시당

2024-01-31 13:47 UTC, alicehrk commented on src/pages/SocialRedirecting.js
> +      alert(`access: ${accessToken} refresh: ${refreshToken}`);
이것도요!

2024-02-11 07:45 UTC, limeojin363 commented on src/pages/Login.js
>      console.log("continueWithApple");
continueWithApple에 있는 console.log는 다음 PR에서 삭제할게요~

2024-02-11 08:50 UTC, merged