Feature/share
PrayHelper/uspray-frontend pull request #239
Opened 2024-02-14 00:34 UTC by graS2e

2024-02-15 07:44 UTC, alicehrk requested changes

2024-02-15 07:44 UTC, alicehrk commented on src/components/Group/GroupDetail/GroupDetail.js
> +  const { groupPrayList, groupNotification, importPray } = useGroupPray(group.id);
`importPray`가 어떤 역할을 하는 건지 좀 더 명확하게 드러나는 변수명이었으면 좋겠어요!

2024-02-15 07:44 UTC, alicehrk commented on src/components/Group/GroupDetail/GroupDetail.js
> +  const isData = Object.keys(groupPrayList).length !== 0;
`isData`도 어떤 data가 있는지 없는지를 검사하는 건지, 변수명을 보고 알 수 있으면 좋을 것 같네용 :)

2024-02-15 07:44 UTC, alicehrk commented on src/pages/Main.js
> +  position: fixed;
`position: fixed;`가 중복해서 들어갔네요!

2024-02-15 07:46 UTC, graS2e commented on src/pages/Main.js
> +  position: fixed;
없앴습니다!

2024-02-15 07:53 UTC, graS2e commented on src/components/Group/GroupDetail/GroupDetail.js
> +  const { groupPrayList, groupNotification, importPray } = useGroupPray(group.id);
`takePersonalPray` 로 변경했습니다!

2024-02-15 07:57 UTC, graS2e commented on src/components/Group/GroupDetail/GroupDetail.js
> +  const isData = Object.keys(groupPrayList).length !== 0;
isGroupPrayListData로 변경했습니당 :)

2024-02-16 01:08 UTC, limeojin363 requested changes

2024-02-16 01:08 UTC, limeojin363 commented on src/components/Main/MainContent.js
> +            >
styled-components 대신 인라인 스타일을 사용하신 이유가 있을까요??

2024-02-16 01:08 UTC, limeojin363 commented on src/components/Main/MainContent.js
> +        }}
조건문이나 반복문이 쓰이는경우 특히, handler 함수를 별도로 선언한 다음 가져다 쓰는 쪽이 가독성에서 좋은 것 같아요.

2024-02-16 04:34 UTC, graS2e commented on src/components/Group/GroupDetail/GroupDetail.js
> +        onClick={() => onInvite()}
수정했습니다!

2024-02-16 05:04 UTC, graS2e commented on src/components/Main/MainContent.js
> +            >
disabled, color를 props로 넘겨서 styled-components 내에서 결정되도록 수정했습니다!!

2024-02-16 05:07 UTC, graS2e commented on src/components/Main/MainContent.js
> +        }}
별도로 선언하도록 수정했습니다.

2024-02-16 05:14 UTC, graS2e commented on src/components/Category/Category.js
>        content: pray.content,
`const { name, categoryName, isPrayedToday, ...selectedPrayInfoSubset } =
      pray;
    setSelectedPrayInfo(selectedPrayInfoSubset);`
    
 이런 식으로 수정하였습니다.

2024-02-16 17:34 UTC, limeojin363 approved these changes
수고하셨습니당

2024-02-19 06:38 UTC, merged