fix: 수정 안 되는 이유 표시
PrayHelper/uspray-frontend pull request #263
Opened 2024-03-05 09:08 UTC by graS2e

기도제목 input이 disable 상태일 때 오류가 있다고 판단하게 돼서, 1.5 때처럼 이유 표시했습니다

2024-03-05 11:51 UTC, alicehrk requested changes

2024-03-05 11:51 UTC, alicehrk commented on src/components/PrayDateCategoryInput/PrayDateCategoryInput.js
> +  color: #75bd62;
`GlobalStyle.js`에 있는 변수명을 활용하는 걸로 수정해주세요!

2024-03-05 14:10 UTC, graS2e commented on src/components/PrayDateCategoryInput/PrayDateCategoryInput.js
> +  color: #75bd62;
고쳤습니다!

2024-03-06 04:28 UTC, alicehrk approved these changes

2024-03-06 04:30 UTC, merged