fix: 공백일 때 button disabled 처리
PrayHelper/uspray-frontend pull request #272
Opened 2024-03-14 08:05 UTC by 200516bb

2024-03-16 14:57 UTC, alicehrk requested changes

2024-03-16 14:57 UTC, alicehrk commented on src/components/PrayDateCategoryInput/PrayDateCategoryInput.js
> +        setInputCount(e.value.slice(0, e.maxLength));
e.value.slice에서 `target`이 빠진 것 같은데 잘 동작하나요..?

2024-03-16 14:57 UTC, alicehrk commented on src/components/PrayDateCategoryInput/PrayDateCategoryInput.js
> +        setInputCount(e.value.slice(0, e.maxLength));
그리고 여기 setInputCount(e.value.slice(0, e.maxLength)); 부분에서 문자열 길이를 설정하는게 아니라 문자열 자체를 설정하고 있는 것 같습니다! 아마 수빈싀가 만든게 아닐수도 있는데 건드는 김에 확인 한번만 부탁드림니다.. 🥹

2024-03-16 15:08 UTC, alicehrk requested changes

2024-03-16 15:08 UTC, alicehrk commented on src/components/PrayDateCategoryInput/PrayDateCategoryInput.js
> +        setInputCount(e.value.slice(0, e.maxLength));
maxLength 접근할 때도 e.target 없는데 괜찮나유..?

2024-03-18 00:36 UTC, 200516bb commented on src/components/PrayDateCategoryInput/PrayDateCategoryInput.js
> +        setInputCount(e.value.slice(0, e.maxLength));
보니까 저 if문에 들어가는 경우가 없는 것 같아서 지워도 상관 없을 것 같습니다! 커밋 올릴게용

2024-03-20 05:59 UTC, alicehrk approved these changes

2024-03-20 08:52 UTC, merged